title: "Mohammad Omar Khursheed"
description: "Personal website of Mohammad Omar Khursheed, MATS Research Scholar."
theme: jekyll-theme-minimal

github:
  is_project_page: false

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:title/

exclude:
  - design-explorations
  - index_industrial.html
  - README.md
